# Generated by Buildr 1.4.7, change to your liking

# Version number for this release
VERSION_NUMBER = "0.2.2"
# Group identifier for your projects
GROUP = "phpunit_codecoverage_display"
COPYRIGHT = "Zsolt Takacs"

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

phpstorm_url = "http://download.jetbrains.com/webide/PhpStorm-EAP-121.12.zip"
phpstorm = artifact("phpstorm:phpstorm:zip:phpstorm:121.12")
download(phpstorm => phpstorm_url)
zip = Unzip.new('lib_phpstorm' => phpstorm).from_path('lib').root.extract

my_layout = Layout.new
my_layout[:source, :main, :java] = 'src'
my_layout[:source, :test, :java] = 'test'

jars = Dir.glob("lib_phpstorm/**/*.jar")
jars << Dir.glob("lib/**/*.jar")

desc "The Phpunit_codecoverage_display project"
define "phpunit_codecoverage_display", :layout=>my_layout do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  test.with jars
  compile.with jars
end
